### ISSUE TITLE
DiCE doesn't change my outcome

### ISSUE THREAD

**Issue by ninaspreitzer** [yuyasugano/dice-test#1]
Hello, 

when I try to run DiCE, the proposed explanations do not change my outcome from 0 to . 
<img width="902" alt="Bildschirmfoto 2022-05-09 um 19 26 05" src="https://user-images.githubusercontent.com/57034840/167464266-e8b1c53d-94b6-4e66-9f73-97d16e045993.png">

any idea what I am doing wrong? 
Cheers

**Comment by yuyasugano** [comment]
@ninaspreitzer Sorry for late. I think this notebook came from DiCE repository and I do not know details. Please raise an isssue in the original repository. Maybe here? https://github.com/interpretml/DiCE/blob/master/docs/source/notebooks/DiCE_getting_started.ipynb
